name: CI/CD Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions :
      id-token : write
      contents : read
      pull-requests : write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Properies Files based on Branch
        run: |
          echo "${{ env.APPLICATION }}" > ./src/main/resources/application.properties
          echo "${{ env.APPLICATION_PROD }}" > ./src/main/resources/application-prod.properties
          fi

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK (gcloud CLI)
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/backend:develop

      - name: Deploy to Compute Engine VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Stopping and removing existing containers..."
            docker stop marong-backend || true
            docker rm marong-backend || true

            echo "Authenticating to Artifact Registry..."
            gcloud auth configure-docker asia-northeast3-docker.pkg.dev

            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/backend:develop

            echo "Starting new container..."
            docker run -d \
              --name marong-backend \
              ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}/backend:develop

            echo "Deployment to Compute Engine VM completed."
            
